```{r}
library(dbscan)
## compare on moons data
data("moons")
DATA_SIZE <- 14
MCS = 3
Labels <- 1:DATA_SIZE

table <- moons[1:DATA_SIZE,]
cl <- dbscan::hdbscan(table, minPts = MCS)
# print the Hierarchical Diagram
dev.new(width=50, height=150, unit="in")
plot(cl$hc)
# print the points
plot(table, col=cl$cluster+1, pch=20, cex = 1.9)
text(table[,1]+0.08, table[,2]+0.008, labels = Labels)
# pig <- cl$hc$height
# print(pig)

```

```{r}
x <- c(10, 25, 25, 40, 40, 55, 55, 70, 85)
y <- c(10, 20, 55, 15, 30, 15, 40, 30, 30)
table <- data.frame(matrix(ncol = 2, nrow = 9))
table[,1] <- x
table[,2] <- y
cl <- dbscan::hdbscan(table, minPts = 2)
plot(cl$hc)
plot(table, col=cl$cluster+1, pch=20, cex = 1.9)
text(table[,1]+0.08, table[,2]+0.008, labels=rownames(table))
a <- cl$hc$height
```

```{r}
library(dbscan)
## compare on moons data
data("moons")
DATA_SIZE <- 10
MCS = 2
Labels <- 1:DATA_SIZE

table <- moons[1:DATA_SIZE,]
cl <- dbscan::hdbscan(table, minPts = MCS)
# print the Hierarchical Diagram
plot(cl$hc)
# print the points
plot(table, col=cl$cluster+1, pch=20, cex = 1.9)
text(table[,1]+0.08, table[,2]+0.008, labels = Labels)
# pig <- cl$hc$height
# print(pig)

```

\
