print("==========================================================================================================")
print(" This is the 1st step for Assignment 4, make sure you have docker setup and running already before moving forward ")
print("==========================================================================================================")
print(">> 1. Sanity check the container, make sure hdfs dfs -ls command works: ")
result <- system("docker exec namenode hdfs dfs -ls /", intern = TRUE)
print(result)
print("==========================================================================================================")
print(">> If you see no error above, then Sanity is passed, your containers are running OK!")
print("==========================================================================================================")
print(">> 2. Going to upload iris.csv file to HDFS in docker, please wait ...")
result <- system("docker cp iris.csv namenode:/", intern = TRUE)
result <- system("docker exec namenode hdfs dfs -put iris.csv /", intern = TRUE)
print("==========================================================================================================")
print(">> 3. Going to upload multishapes.csv file to HDFS in docker, please wait ...")
result <- system("docker cp multishapes.csv namenode:/", intern = TRUE)
result <- system("docker exec namenode hdfs dfs -put multishapes.csv /", intern = TRUE)
print("==========================================================================================================")
result <- system("docker exec namenode hdfs dfs -ls /", intern = TRUE)
print(result)
print("==========================================================================================================")
print(" >> Please make sure the printout above have iris.csv and multishapes.csv file.")
print(" >> If these two files are there, then we are all good for the 1st step now!")
print("==========================================================================================================")
